production: retrain
gpu_list:
- 0
- 1
backup_time: '00_00'
pcb_dataset_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset
pcb_data_dir: /home/aoi/AOI_PCB_Retrain_my/pcb_data
old_model_dir: /home/aoi/AOI_PCB_Retrain_my/models/old
train_data_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/train_data
val_data_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/val_data
test_data_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/test_data
retrain_data_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/retrain_data
retrain_data_org_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/retrain_data/original
retrain_data_org_pre_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/retrain_data/original_preprocess
retrain_data_train_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/retrain_data/train
retrain_data_val_dir: /home/aoi/AOI_PCB_Retrain_my/pcb-dataset/retrain_data/val
benchmark_dir: /home/aoi/AOI_PCB_Retrain_my/hp_janet_benchmark
ensemble_dir: /home/aoi/AOI_PCB_Retrain_my/ensemble
ensemble_result_dir: /home/aoi/AOI_PCB_Retrain_my/ensemble/2022_11_29
image_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_img
image_backup_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_img_backup
image_wo_border_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_img_wo_border
inference_result_image_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_result_img
inference_result_image_backup_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_result_img_backup
inference_result_label_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_result_json
inference_result_txt_dir: /home/aoi/AOI_PCB_Retrain_my/inference_result/factory_result_txt
inference_log_file_path: /home/aoi/AOI_PCB_Retrain_my/inference_result/inference_result.log
centernet2_yaml_file_path: /home/aoi/AOI_PCB_Retrain_my/detectron2/projects/CenterNet2/configs/ctr2_retrain1_bs8_20211027.yaml
centernet2_old_model_file_path: /home/aoi/AOI_PCB_Retrain_my/models/old/CenterNet2/centernet2_2021_12_24.pth
centernet2_best_model_file_path: /home/aoi/AOI_PCB_Retrain_my/models/old/CenterNet2/centernet2_2021_12_24.pth
centernet2_model_output_dir: /home/aoi/AOI_PCB_Retrain_my/detectron2/CenterNet2_2022_11_29_output
centernet2_model_output_version: CenterNet2_2022_11_29
centernet2_new_model_file_dir: /home/aoi/AOI_PCB_Retrain_my/models/2022_11_29/CenterNet2
centernet2_old_model_label_dir: null
centernet2_best_model_label_dir: null
retinanet_yaml_file_path: /home/aoi/AOI_PCB_Retrain_my/detectron2/configs/COCO-Detection/retinanet_R_101_FPN_3x_PCB.yaml
retinanet_old_model_file_path: /home/aoi/AOI_PCB_Retrain_my/models/old/RetinaNet/retinanet_2021_12_24.pth
retinanet_best_model_file_path: /home/aoi/AOI_PCB_Retrain_my/models/old/RetinaNet/retinanet_2021_12_24.pth
retinanet_model_output_dir: /home/aoi/AOI_PCB_Retrain_my/detectron2/RetinaNet_2022_11_29_output
retinanet_model_output_version: RetinaNet_2022_11_29
retinanet_new_model_file_dir: /home/aoi/AOI_PCB_Retrain_my/models/2022_11_29/RetinaNet
retinanet_old_model_label_dir: null
retinanet_best_model_label_dir: null
yolov4_data_file_path: /home/aoi/AOI_PCB_Retrain_my/YOLOv4/cfg/pcb.data
yolov4_cfg_file_path: /home/aoi/AOI_PCB_Retrain_my/YOLOv4/cfg/yolov4-pcb.cfg
yolov4_old_model_file_path: /home/aoi/AOI_PCB_Retrain_my/models/old/YoloV4/yolov4_2021_12_24.weights
yolov4_best_model_file_path: /home/aoi/AOI_PCB_Retrain_my/models/old/YoloV4/yolov4_2021_12_24.weights
yolov4_model_output_dir: /home/aoi/AOI_PCB_Retrain_my/YOLOv4/weights/YoloV4_2022_11_29
yolov4_model_output_version: YoloV4_2022_11_29
yolov4_new_model_file_dir: /home/aoi/AOI_PCB_Retrain_my/models/2022_12_01/YoloV4
yolov4_old_model_label_dir: null
yolov4_best_model_label_dir: null
crop_w: 512
crop_h: 512
margin: 100
